classes=c("character", "character", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric")
dataset=read.table("household_power_consumption.txt",header=TRUE,sep = ";",dec = ".",colClasses = classes,fill=TRUE,na.strings=c("?"))
dataset$Date=as.Date(dataset$Date,format = "%d/%m/%Y")
dataSet=subset(dataset,dataset$Date==as.Date("01/02/2007",format = "%d/%m/%Y") | dataset$Date==as.Date("02/02/2007",format = "%d/%m/%Y"))
dataSet$DateTime=as.POSIXct(paste(dataSet$Date, dataSet$Time), format="%Y-%m-%d %H:%M:%S")
png(filename = "plot3.png",width = 480,height = 480)
plot(dataSet$Sub_metering_1~dataSet$DateTime, type="l", xlab = "", ylab="Energy sub metering", col="black")
lines(dataSet$Sub_metering_2~dataSet$DateTime, type = "l", col="red")
lines(dataSet$Sub_metering_3~dataSet$DateTime, type = "l", col="blue")
legend("topright", names(dataSet)[7:9], lty=1, lwd=2,col=c("black","red","blue"))
dev.off()
